language: node_js
node_js:
  - "stable"

cache:
  directories:
    - node_modules

script:
  - yarn test:unit
  - yarn build

deploy:
  - provider: surge
    skip_cleanup: true
    domain: https://pizzaria.surge.sh
    project: ./dist/
    on:
      branch: master
  - provider: surge
    skip_cleanup: true
    domain: https://dev-pizzaria.surge.sh
    project: ./dist/
    on:
      branch: development
