export const MUTATIONS = {
  SET_SIZES: "SET_SIZES",
  SET_FLAVORS: "SET_FLAVORS",
  SET_ADD_ONS: "SET_ADD_ONS",
  SET_ORDER_STEP: "SET_ORDER_STEP"
};

export const ACTIONS = {
  GET_SIZES: "GET_SIZES",
  GET_FLAVORS: "GET_FLAVORS",
  GET_ADD_ONS: "GET_ADD_ONS"
};
